display_name: null
engine:
  type: GlobusComputeEngine
  max_workers_per_node: 1
  strategy: simple
  address:
    type: address_by_interface
    ifname: hsn0

  provider:
    type: SlurmProvider
    partition: debug
    launcher:
      type: SimpleLauncher
    account: "hacc"
    scheduler_options: |
      #SBATCH --constraint=cpu\
      #SBATCH --ntasks-per-node=16
    worker_init: |
      export OMP_PROC_BIND=spread
      export OMP_PLACES=threads
      export OMP_NUM_THREADS=8
      export HCP_SYSTEM=PERLMUTTER
      export HCP_WORKING_BASE=/global/cfs/cdirs/hacc/OpenCosmo/$(whoami)/
      export HCP_RESULT_BASE=/global/cfs/cdirs/hacc/gsharing/OpenCosmo/ComputePortal
      export HCP_RESULT_COLLECTION_UUID=442c25cc-0b44-41c4-a9a2-661e9afaea4c
      export HCP_RESULT_COLLECTION_PATH=ComputePortal/
      export HCP_RESULT_COLLECTION_URL=https://g-5018f2.6b7bd8.0ec8.data.globus.org/ComputePortal
      source ~/hacc-compute-portal/hcp_endpoint/env/perlmutter.env.sh
      source ~/hacc-compute-portal/hcp_endpoint/.venv/bin/activate
      cd ~
    walltime: 00:30:00
    cmd_timeout: 120

    nodes_per_block: 1
    init_blocks: 0
    max_blocks: 1
    min_blocks: 0
